# Generated by Django 5.0.6 on 2024-06-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_feedbackform_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='parent_email',
            field=models.EmailField(default='parent_email@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='parent_phone',
            field=models.CharField(default='89000000000', max_length=15),
            preserve_default=False,
        ),
    ]
